# Generated by Django 5.0.3 on 2024-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_board', '0002_task_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='board_column',
            field=models.CharField(choices=[('board-column-todo', 'board-column-todo'), ('board-column-progress', 'board-column-progress'), ('board-column-feedback', 'board-column-feedback'), ('board-column-done', 'board-column-done')], default='board-column-todo', max_length=21),
        ),
    ]
