# Generated by Django 5.0.3 on 2024-03-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_board', '0005_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board_column',
            field=models.CharField(choices=[('board-column-todo', 'To Do'), ('board-column-progress', 'In Progress'), ('board-column-feedback', 'Feedback'), ('board-column-done', 'Done')], default='board-column-todo', max_length=21),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('mid', 'Mid'), ('low', 'Low')], default='low', max_length=7),
        ),
    ]
