# Generated by Django 5.0.3 on 2024-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_board', '0006_alter_task_board_column_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('rgb(255, 0, 0)', 'Red'), ('rgb(60, 179, 113)', 'Green'), ('#0000FF', 'Blue'), ('rgb(255, 165, 0)', 'Yellow'), ('rgb(0, 0, 255)', 'Cyan')], default='#FF0000', max_length=17),
        ),
    ]
