# Generated by Django 5.0.3 on 2024-04-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_board', '0008_alter_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('rgba(255, 0, 0, 0.4)', 'Red'), ('rgba(60, 179, 113, 0.4)', 'Green'), ('rgba(0, 0, 255, 0.4)', 'Blue'), ('rgba(255, 165, 0, 0.4)', 'Yellow'), ('rgba(0, 255, 255, 0.4)', 'Cyan')], default='#FF0000', max_length=23),
        ),
    ]
