# Generated by Django 5.0.3 on 2024-04-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_board', '0009_alter_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('cyan', 'Cyan')], default='#FF0000', max_length=23),
        ),
    ]
