# Generated by Django 5.0.3 on 2024-05-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_board', '0010_alter_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
