# Generated by Django 5.0.3 on 2024-05-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_board', '0012_alter_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author_username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
