# Generated by Django 5.0.3 on 2024-05-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_board', '0013_task_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
